from types import SimpleNamespace

HYPERPARAMS = {'lander':SimpleNamespace(**
                    {'env_id'      : 'LunarLander-v2',
                     'n_envs'      : 2,
                     'SEED'        : 144,
                     'EPS_START'   : 1.0,
                     'EPS_END'     : 0.02,
                     'EPS_FRAMES'  : 25_000,
                     'OBS_SIZE'    : 8,
                     'ACT_SIZE'    : 4,
                     'HID_SIZE'    : 348,
                     'GAMMA'       : 0.99,
                     'STEPS'       : 1,
                     'BUFFER_SIZE' : 200_000,
                     'INIT_REPLAY' : 10_000,
                     'LR'          : 1e-3,
                     'N_MP'        : 4,
                     'BATCH_SIZE'  : 256,
                     'VMIN'        : -500,
                     'VMAX'        : 300,
                     'NATOMS'      : 51,
                     'BOUND_SOLVE' : 200,
                     'SYNC_NET'    : 1000
                     }),
               'cartpole':SimpleNamespace(**
                    {'ENV_ID'      : 'CartPole-v0',
                     'N_ENVS'      : 1,
                     'SEED'        : 144,
                     'EPS_START'   : 1.0,
                     'EPS_END'     : 0.02,
                     'EPS_FRAMES'  : 5_000,
                     'OBS_SIZE'    : 4,
                     'ACT_SIZE'    : 2,
                     'HID_SIZE'    : 128,
                     'GAMMA'       : 0.99,
                     'STEPS'       : 4,
                     'BUFFER_SIZE' : 15_000,
                     'INIT_REPLAY' : 3_000,
                     'LR'          : 1e-3,
                     'N_MP'        : 1,
                     'BATCH_SIZE'  : 256,
                     'VMIN'        : 0,
                     'VMAX'        : 200,
                     'NATOMS'      : 51,
                     'BOUND_SOLVE' : 195,
                     'SYNC_NET'    : 1000
                     }),
               'mountaincar':SimpleNamespace(**
                    {'env_id'      : 'MountainCar-v0',
                     'n_envs'      : 4,
                     'seed'        : 124,
                     'eps_start'   : 1.0,
                     'eps_end'     : 0.02,
                     'eps_frames'  : 5_000,
                     'obs_size'    : 2,
                     'act_size'    : 3,
                     'hid_size'    : 128,
                     'gamma'       : 0.99,
                     'steps'       : 2,
                     'buffer_size' : 50_000,
                     'init_replay' : 5_000,
                     'lr'          : 1e-3,
                     'n_mp'        : 1,
                     'batch_size'  : 64,
                     'vmin'        : 0,
                     'vmax'        : 100,
                     'natoms'      : 51,
                     'bound_solve' : 95,
                     'sync_net'    : 1000
                     }),
               'lander1':SimpleNamespace(**
                    {'env_id'      : 'LunarLander-v2',
                     'n_envs'      : 4,
                     'seed'        : 124,
                     'eps_start'   : 1.0,
                     'eps_end'     : 0.02,
                     'eps_frames'  : 30_000,
                     'obs_size'    : 8,
                     'act_size'    : 4,
                     'hid_size'    : 128,
                     'gamma'       : 0.99,
                     'steps'       : 5,
                     'buffer_size' : 50_000,
                     'init_replay' : 5_000,
                     'lr'          : 1e-3,
                     'n_mp'        : 1,
                     'batch_size'  : 64,
                     'vmin'        : -100,
                     'vmax'        : 100,
                     'natoms'      : 51,
                     'bound_solve' : 195,
                     'sync_net'    : 1000
                     }),
    }